### ISSUE TITLE
[Feature] Adding Contimous Integration (including creating an executable jar and execution of all unit tests)

### ISSUE THREAD

**Issue by HannesSttzr** [ccd-course/chess_backend#11]
Tasks:
- Configuring your CI-server to clone the current revision of your code-repository
- Configuring your CI-server to invoke your build-system to compile your sources
- Adapt your build configuration to produce an executable Jar of the JChess-project. 
- Add the Javadoc-generation to your build script and create the Javadoc html webpages as an artifact
- Configure your build server to automatically execute all unit tests upon successful compilation. This includes parsing
and displaying test results

**Comment by v411e** [comment]
I would say this issue can be closed, right @HannesSttzr ?
