### ISSUE TITLE
[Feature] Pawn promotion

### ISSUE THREAD

**Issue by v411e** [ccd-course/chess_backend#119]
Epic:
- As a user I want to have the option to promote my pawn to another piece when it reaches the "end of the board", so that I can relate to the common chess rules.

Acceptance:
- The pawn gets ranked up if he moves forward.
- The pawn gets automatically promoted to a queen if he reaches the maximum rank.

**Comment by HannesSttzr** [comment]
There are 2 options:
- promotion to queen, rook, knight or bishop and the player can choose it
- automatical promotion to queen (a statistic says that 96.9% of the promotion is to a queen)
