### ISSUE TITLE
[Fix] ChessboardService has some problems

### ISSUE THREAD

**Issue by HannesSttzr** [ccd-course/chess_backend#41]
Run and debug the chessboardService
- in GameService the chessboardService is not getting initialized, the variable stays null
- in ChessboardService in method setPiece in line 52
   - pozX=0 and pozY=0
   - square = Squares[0][0] = null
   - so line 53 throws a NullPointerException

**Comment by AmrAnwar** [comment]
@HannesSttzr I guess chessboardService is null because we created the GameService manually not by Spring:
```
    private static final GameService gameController = new GameService();
```
I'll try to fix it for now but later we need to make it work with @Autowire(Depencey Injection) like other services as well
